
import React, { useState } from 'react';
import { Plus, Search, Edit2, Trash2, Shield, User as UserIcon } from 'lucide-react';
import { useApp } from '../context/AppProvider';
import { Input } from '../components/ui/Input';
import { User, UserRole } from '../types';

export const Users = () => {
    const { usersList, addUser, updateUser, deleteUser } = useApp();
    const [searchTerm, setSearchTerm] = useState('');
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingUser, setEditingUser] = useState<User | null>(null);

    const [formData, setFormData] = useState({
        name: '',
        email: '',
        role: 'agent' as UserRole
    });

    const filteredUsers = usersList.filter(user =>
        user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
        user.email.toLowerCase().includes(searchTerm.toLowerCase())
    );

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (editingUser) {
            await updateUser(editingUser.id, formData);
        } else {
            await addUser({
                id: '', // Will be generated by DB
                ...formData
            });
        }
        closeModal();
    };

    const openModal = (user?: User) => {
        if (user) {
            setEditingUser(user);
            setFormData({
                name: user.name,
                email: user.email,
                role: user.role
            });
        } else {
            setEditingUser(null);
            setFormData({
                name: '',
                email: '',
                role: 'agent'
            });
        }
        setIsModalOpen(true);
    };

    const closeModal = () => {
        setIsModalOpen(false);
        setEditingUser(null);
    };

    const handleDelete = (id: string) => {
        if (confirm('Tem certeza que deseja excluir este usuário?')) {
            deleteUser(id);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-between items-center px-1">
                <div>
                    <h1 className="text-2xl font-black text-foreground uppercase tracking-tighter italic">Usuários do <span className="text-primary">Sistema</span></h1>
                    <p className="text-muted-foreground font-bold text-[9px] md:text-[10px] uppercase tracking-widest mt-1 italic">Gerencie quem tem acesso ao painel administrativo.</p>
                </div>
                <button
                    onClick={() => openModal()}
                    className="bg-primary/10 text-primary border border-primary/20 hover:bg-primary hover:text-primary-foreground px-4 py-2 rounded-xl flex items-center gap-2 transition-all font-black uppercase italic text-xs"
                >
                    <Plus size={20} />
                    Novo Usuário
                </button>
            </div>

            <div className="premium-card !rounded-[2rem] overflow-hidden flex flex-col border border-white/10">
                <div className="p-4 border-b border-white/10 bg-secondary/30 backdrop-blur-md">
                    <Input
                        icon={<Search size={18} />}
                        placeholder="BUSCAR POR NOME OU EMAIL..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                        className="uppercase tracking-widest text-[10px] font-black italic"
                    />
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full text-left border-separate border-spacing-0">
                        <thead className="bg-secondary/50 sticky top-0 z-20 shadow-sm backdrop-blur-md">
                            <tr>
                                <th className="px-8 py-5 text-[10px] font-black text-muted-foreground uppercase tracking-[0.2em] border-b border-white/10 italic">Nome</th>
                                <th className="px-8 py-5 text-[10px] font-black text-muted-foreground uppercase tracking-[0.2em] border-b border-white/10 italic">Email</th>
                                <th className="px-8 py-5 text-[10px] font-black text-muted-foreground uppercase tracking-[0.2em] border-b border-white/10 italic">Função</th>
                                <th className="px-8 py-5 text-right border-b border-white/10 italic">Ações</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-white/5">
                            {filteredUsers.map((user) => (
                                <tr key={user.id} className="hover:bg-secondary/30 transition-colors group">
                                    <td className="px-8 py-4 whitespace-nowrap">
                                        <div className="flex items-center gap-3">
                                            <div className="w-9 h-9 rounded-xl bg-secondary flex items-center justify-center text-primary border border-white/10 group-hover:border-primary/40 transition-all">
                                                {user.role === 'admin' ? <Shield size={16} /> : <UserIcon size={16} />}
                                            </div>
                                            <span className="font-bold text-foreground uppercase italic tracking-tight">{user.name}</span>
                                        </div>
                                    </td>
                                    <td className="px-8 py-4 whitespace-nowrap text-muted-foreground font-medium italic text-xs">{user.email}</td>
                                    <td className="px-8 py-4 whitespace-nowrap">
                                        <span className={`inline-flex items-center px-3 py-1 rounded-lg text-[9px] font-black uppercase tracking-widest italic border ${user.role === 'admin'
                                            ? 'bg-primary/10 text-primary border-primary/30'
                                            : 'bg-emerald-500/10 text-emerald-500 border-emerald-500/30'
                                            }`}>
                                            {user.role === 'admin' ? 'Administrador' : 'Corretor'}
                                        </span>
                                    </td>
                                    <td className="px-8 py-4 whitespace-nowrap text-right">
                                        <div className="flex items-center justify-end gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                            <button
                                                onClick={() => openModal(user)}
                                                className="p-2 text-muted-foreground hover:text-primary transition-all rounded-lg hover:bg-primary/10"
                                                title="Editar"
                                            >
                                                <Edit2 size={16} />
                                            </button>
                                            <button
                                                onClick={() => handleDelete(user.id)}
                                                className="p-2 text-muted-foreground hover:text-red-500 transition-all rounded-lg hover:bg-red-500/10"
                                                title="Excluir"
                                            >
                                                <Trash2 size={16} />
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                            {filteredUsers.length === 0 && (
                                <tr>
                                    <td colSpan={4} className="px-8 py-14 text-center text-muted-foreground text-[10px] font-black uppercase tracking-widest italic opacity-40">
                                        Nenhum usuário encontrado.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Modal */}
            {isModalOpen && (
                <div className="fixed inset-0 bg-background/80 backdrop-blur-xl flex items-center justify-center z-50 p-4">
                    <div className="bg-card rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-in fade-in zoom-in duration-200 border border-white/10">
                        <div className="px-8 py-5 border-b border-white/10 flex justify-between items-center bg-secondary/30">
                            <h3 className="text-sm font-black text-foreground uppercase tracking-widest italic">
                                {editingUser ? 'Editar' : 'Novo'} <span className="text-primary">Usuário</span>
                            </h3>
                            <button onClick={closeModal} className="w-8 h-8 flex items-center justify-center rounded-lg bg-secondary text-muted-foreground hover:text-foreground transition-all">
                                &times;
                            </button>
                        </div>

                        <form onSubmit={handleSubmit} className="p-8 space-y-6">
                            <div className="space-y-4">
                                <Input
                                    label="NOME COMPLETO"
                                    required
                                    value={formData.name}
                                    onChange={e => setFormData({ ...formData, name: e.target.value })}
                                />

                                <Input
                                    label="E-MAIL DE ACESSO"
                                    type="email"
                                    required
                                    value={formData.email}
                                    onChange={e => setFormData({ ...formData, email: e.target.value })}
                                />
                                <p className="text-[9px] text-muted-foreground uppercase font-black tracking-widest italic mt-1 ml-1">Usado para identificação e login no sistema.</p>

                                <div className="space-y-2">
                                    <label className="block text-[10px] font-black text-muted-foreground uppercase tracking-widest ml-1 italic">Função Administrativa</label>
                                    <select
                                        value={formData.role}
                                        onChange={e => setFormData({ ...formData, role: e.target.value as UserRole })}
                                        className="w-full h-[46px] px-4 rounded-xl border border-white/10 bg-secondary text-foreground text-xs font-bold focus:outline-none focus:ring-2 focus:ring-primary/20 appearance-none uppercase transition-all"
                                    >
                                        <option value="agent">Corretor (Acesso Limitado)</option>
                                        <option value="admin">Administrador (Acesso Total)</option>
                                    </select>
                                </div>
                            </div>

                            <div className="pt-4 flex gap-3">
                                <button
                                    type="button"
                                    onClick={closeModal}
                                    className="flex-1 px-4 py-3 border border-white/10 rounded-xl text-muted-foreground font-black uppercase italic text-[10px] tracking-widest hover:bg-secondary transition-all"
                                >
                                    Cancelar
                                </button>
                                <button
                                    type="submit"
                                    className="flex-1 px-4 py-3 bg-primary text-primary-foreground rounded-xl font-black uppercase italic text-[10px] tracking-widest hover:brightness-110 transition-all shadow-lg shadow-primary/20"
                                >
                                    Salvar Usuário
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
};
